// <auto-generated />
using System;
using Events.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Events.API.Migrations
{
    [DbContext(typeof(EventContext))]
    partial class EventContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventPlatform.Domen.Lokacija", b =>
                {
                    b.Property<int>("LokacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LokacijaID"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LokacijaID");

                    b.ToTable("Lokacije");
                });

            modelBuilder.Entity("EventPlatform.Domen.Predavac", b =>
                {
                    b.Property<int>("PredavacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredavacID"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OblastStrucnosti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PredavacID");

                    b.ToTable("Predavaci");
                });

            modelBuilder.Entity("EventPlatform.Domen.StrucniDogadjaj", b =>
                {
                    b.Property<int>("StrucniDogadjajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StrucniDogadjajID"));

                    b.Property<string>("Agenda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CenaKotizacije")
                        .HasColumnType("float");

                    b.Property<DateTime>("DatumVremeOdrzavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("LokacijaID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipDogadjajaID")
                        .HasColumnType("int");

                    b.Property<double>("Trajanje")
                        .HasColumnType("float");

                    b.HasKey("StrucniDogadjajID");

                    b.HasIndex("LokacijaID");

                    b.HasIndex("TipDogadjajaID");

                    b.ToTable("StrucniDogadjaji");
                });

            modelBuilder.Entity("EventPlatform.Domen.TipDogadjaja", b =>
                {
                    b.Property<int>("TipDogadjajaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipDogadjajaID"));

                    b.Property<string>("NazivTipa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipDogadjajaID");

                    b.ToTable("TipoviDogadjaja");
                });

            modelBuilder.Entity("StrucniDogadjajiPredavaci", b =>
                {
                    b.Property<int>("PredavacID")
                        .HasColumnType("int");

                    b.Property<int>("StrucniDogadjajID")
                        .HasColumnType("int");

                    b.HasKey("PredavacID", "StrucniDogadjajID");

                    b.HasIndex("StrucniDogadjajID");

                    b.ToTable("StrucniDogadjajiPredavaci");
                });

            modelBuilder.Entity("EventPlatform.Domen.StrucniDogadjaj", b =>
                {
                    b.HasOne("EventPlatform.Domen.Lokacija", "Lokacija")
                        .WithMany("StrucniDogadjaji")
                        .HasForeignKey("LokacijaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventPlatform.Domen.TipDogadjaja", "TipDogadjaja")
                        .WithMany("StrucniDogadjaji")
                        .HasForeignKey("TipDogadjajaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lokacija");

                    b.Navigation("TipDogadjaja");
                });

            modelBuilder.Entity("StrucniDogadjajiPredavaci", b =>
                {
                    b.HasOne("EventPlatform.Domen.Predavac", null)
                        .WithMany()
                        .HasForeignKey("PredavacID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventPlatform.Domen.StrucniDogadjaj", null)
                        .WithMany()
                        .HasForeignKey("StrucniDogadjajID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EventPlatform.Domen.Lokacija", b =>
                {
                    b.Navigation("StrucniDogadjaji");
                });

            modelBuilder.Entity("EventPlatform.Domen.TipDogadjaja", b =>
                {
                    b.Navigation("StrucniDogadjaji");
                });
#pragma warning restore 612, 618
        }
    }
}
