// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prijave.API.Data;

#nullable disable

namespace Prijave.API.Migrations
{
    [DbContext(typeof(PrijavaContext))]
    partial class PrijavaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prijave.API.Models.Prijava", b =>
                {
                    b.Property<int>("UcesnikID")
                        .HasColumnType("int");

                    b.Property<int>("StrucniDogadjajID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.HasKey("UcesnikID", "StrucniDogadjajID");

                    b.ToTable("Prijave");
                });

            modelBuilder.Entity("Prijave.API.Models.Ucesnik", b =>
                {
                    b.Property<int>("UcesnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UcesnikID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UcesnikID");

                    b.ToTable("Ucesnici");
                });

            modelBuilder.Entity("Prijave.API.Models.Prijava", b =>
                {
                    b.HasOne("Prijave.API.Models.Ucesnik", "Ucesnik")
                        .WithMany("Prijave")
                        .HasForeignKey("UcesnikID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ucesnik");
                });

            modelBuilder.Entity("Prijave.API.Models.Ucesnik", b =>
                {
                    b.Navigation("Prijave");
                });
#pragma warning restore 612, 618
        }
    }
}
