// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Placanja.API.Data;

#nullable disable

namespace Placanja.API.Migrations
{
    [DbContext(typeof(PlacanjaContext))]
    [Migration("20260614073521_AddEventSourcing")]
    partial class AddEventSourcing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Placanja.API.Models.EventSourcing.EventStoreRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AggregateId")
                        .HasColumnType("int");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EventStoreRecords");
                });

            modelBuilder.Entity("Placanja.API.Models.EventSourcing.SnapshotStoreRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AggregateId")
                        .HasColumnType("int");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SnapshotStoreRecords");
                });

            modelBuilder.Entity("Placanja.API.Models.RacunUcesnika", b =>
                {
                    b.Property<int>("UcesnikID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StanjeNaRacunu")
                        .HasColumnType("float");

                    b.HasKey("UcesnikID");

                    b.ToTable("RacuniUcesnika");

                    b.HasData(
                        new
                        {
                            UcesnikID = 1,
                            Email = "aleksa@example.com",
                            Ime = "Aleksa",
                            Prezime = "Jovanovic",
                            StanjeNaRacunu = 5000.0
                        },
                        new
                        {
                            UcesnikID = 2,
                            Email = "marko@example.com",
                            Ime = "Marko",
                            Prezime = "Markovic",
                            StanjeNaRacunu = 50.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
